var animalList = [
  {
    Name: "Wishbone",
    Type: "Dog",
    Breed: "Australian Shephard Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 1,
      Weeks: 2,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 20579,
      MicroChipNo: 985113004709947,
    },
    Suitability: "",
    AbtMe:
      "Wishbone is a super sweet playful guy! He is around a 2 years old, but is still very much a puppy. He loves people and he, like any youngster, will need basic manner training and a patient home willing to put their time and energy into him. Wishbone also seems to play well with other dogs! His perfect doggy pal would be one that can keep up yet be tolerant of his playful antics. He would benefit from a home willing to exhaust his energy and keep him active . Wishbone might jump on you or play mouth because he is young and still learning. Wishbone will require a home with children 13 years and older because he gets so playful and excited he doesn't realize his size and strength. He truly is a smart young man just needs the right home to spoil him rotten! My past owner went through the process of getting me registered as an Emotional Support Animal as well! And I have the Certificate to prove it!",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/69695.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2d2c50cb-6751-4532-a398-877422a56c44.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/ae164deb-1077-426f-bace-f38307138814.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/c95a20b7-54d9-43a4-a541-159f9eb39a51.jpeg",
    ],
  },
  {
    Name: "Pepper",
    Type: "Dog",
    Breed: "American Pit Bull Cross",
    SecondBreed: "",
    Sex: "Female",
    Color: "White",
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 2,
      Weeks: 4,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23328,
      MicroChipNo: 985113005872880,
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com//photos/lostfound/71168_th_600.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/5ff135bb-000e-4220-8aa0-790af95892c0.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/334112a8-a782-403c-8ea0-36e490a1a486.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2004c2ad-2bf6-4661-90c5-1bcd3378529f.jpg",
    ],
  },
  {
    Name: "Fernando",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23907,
      MicroChipNo: 985113006286714,
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71393.jpg",
    ],
  },
  {
    Name: "Hemingway",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23897,
      MicroChipNo: "",
    },
    Suitability: "<br>Doesn't Like Cats<br>Special Needs",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71387.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/42c9c930-fb07-445b-a08e-cd83c438c515.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/9d5a88d5-bfd5-4d78-b7cd-8e91bdda0bdd.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/34d4696f-2735-4a6e-b266-210357ff5d74.jpeg",
    ],
  },
  {
    Name: "Hemingway",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23897,
      MicroChipNo: "",
    },
    Suitability: "<br>Doesn't Like Cats<br>Special Needs",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71387.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/42c9c930-fb07-445b-a08e-cd83c438c515.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/9d5a88d5-bfd5-4d78-b7cd-8e91bdda0bdd.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/34d4696f-2735-4a6e-b266-210357ff5d74.jpeg",
    ],
  },
  {
    Name: "Wishbone",
    Type: "Dog",
    Breed: "Australian Shephard Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 1,
      Weeks: 2,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 20579,
      MicroChipNo: 985113004709947,
    },
    Suitability: "",
    AbtMe:
      "Wishbone is a super sweet playful guy! He is around a 2 years old, but is still very much a puppy. He loves people and he, like any youngster, will need basic manner training and a patient home willing to put their time and energy into him. Wishbone also seems to play well with other dogs! His perfect doggy pal would be one that can keep up yet be tolerant of his playful antics. He would benefit from a home willing to exhaust his energy and keep him active . Wishbone might jump on you or play mouth because he is young and still learning. Wishbone will require a home with children 13 years and older because he gets so playful and excited he doesn't realize his size and strength. He truly is a smart young man just needs the right home to spoil him rotten! My past owner went through the process of getting me registered as an Emotional Support Animal as well! And I have the Certificate to prove it!",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/69695.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2d2c50cb-6751-4532-a398-877422a56c44.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/ae164deb-1077-426f-bace-f38307138814.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/c95a20b7-54d9-43a4-a541-159f9eb39a51.jpeg",
    ],
  },
  {
    Name: "Pepper",
    Type: "Dog",
    Breed: "American Pit Bull Cross",
    SecondBreed: "",
    Sex: "Female",
    Color: "White",
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 2,
      Weeks: 4,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23328,
      MicroChipNo: 985113005872880,
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com//photos/lostfound/71168_th_600.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/5ff135bb-000e-4220-8aa0-790af95892c0.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/334112a8-a782-403c-8ea0-36e490a1a486.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2004c2ad-2bf6-4661-90c5-1bcd3378529f.jpg",
    ],
  },
  {
    Name: "Fernando",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23907,
      MicroChipNo: 985113006286714,
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71393.jpg",
    ],
  },
  {
    Name: "Hemingway",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23897,
      MicroChipNo: "",
    },
    Suitability: "<br>Doesn't Like Cats<br>Special Needs",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71387.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/42c9c930-fb07-445b-a08e-cd83c438c515.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/9d5a88d5-bfd5-4d78-b7cd-8e91bdda0bdd.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/34d4696f-2735-4a6e-b266-210357ff5d74.jpeg",
    ],
  },
  {
    Name: "Hemingway",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23897,
      MicroChipNo: "",
    },
    Suitability: "<br>Doesn't Like Cats<br>Special Needs",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71387.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/42c9c930-fb07-445b-a08e-cd83c438c515.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/9d5a88d5-bfd5-4d78-b7cd-8e91bdda0bdd.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/34d4696f-2735-4a6e-b266-210357ff5d74.jpeg",
    ],
  },
  {
    Name: "Wishbone",
    Type: "Dog",
    Breed: "Australian Shephard Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 1,
      Weeks: 2,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 20579,
      MicroChipNo: 985113004709947,
    },
    Suitability: "",
    AbtMe:
      "Wishbone is a super sweet playful guy! He is around a 2 years old, but is still very much a puppy. He loves people and he, like any youngster, will need basic manner training and a patient home willing to put their time and energy into him. Wishbone also seems to play well with other dogs! His perfect doggy pal would be one that can keep up yet be tolerant of his playful antics. He would benefit from a home willing to exhaust his energy and keep him active . Wishbone might jump on you or play mouth because he is young and still learning. Wishbone will require a home with children 13 years and older because he gets so playful and excited he doesn't realize his size and strength. He truly is a smart young man just needs the right home to spoil him rotten! My past owner went through the process of getting me registered as an Emotional Support Animal as well! And I have the Certificate to prove it!",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/69695.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2d2c50cb-6751-4532-a398-877422a56c44.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/ae164deb-1077-426f-bace-f38307138814.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/c95a20b7-54d9-43a4-a541-159f9eb39a51.jpeg",
    ],
  },
  {
    Name: "Pepper",
    Type: "Dog",
    Breed: "American Pit Bull Cross",
    SecondBreed: "",
    Sex: "Female",
    Color: "White",
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 2,
      Weeks: 4,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23328,
      MicroChipNo: 985113005872880,
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com//photos/lostfound/71168_th_600.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/5ff135bb-000e-4220-8aa0-790af95892c0.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/334112a8-a782-403c-8ea0-36e490a1a486.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2004c2ad-2bf6-4661-90c5-1bcd3378529f.jpg",
    ],
  },
  {
    Name: "Fernando",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23907,
      MicroChipNo: 985113006286714,
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71393.jpg",
    ],
  },
  {
    Name: "Hemingway",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23897,
      MicroChipNo: "",
    },
    Suitability: "<br>Doesn't Like Cats<br>Special Needs",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71387.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/42c9c930-fb07-445b-a08e-cd83c438c515.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/9d5a88d5-bfd5-4d78-b7cd-8e91bdda0bdd.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/34d4696f-2735-4a6e-b266-210357ff5d74.jpeg",
    ],
  },
  {
    Name: "Hemingway",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23897,
      MicroChipNo: "",
    },
    Suitability: "<br>Doesn't Like Cats<br>Special Needs",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71387.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/42c9c930-fb07-445b-a08e-cd83c438c515.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/9d5a88d5-bfd5-4d78-b7cd-8e91bdda0bdd.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/34d4696f-2735-4a6e-b266-210357ff5d74.jpeg",
    ],
  },
  {
    Name: "Wishbone",
    Type: "Dog",
    Breed: "Australian Shephard Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 1,
      Weeks: 2,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 20579,
      MicroChipNo: 985113004709947,
    },
    Suitability: "",
    AbtMe:
      "Wishbone is a super sweet playful guy! He is around a 2 years old, but is still very much a puppy. He loves people and he, like any youngster, will need basic manner training and a patient home willing to put their time and energy into him. Wishbone also seems to play well with other dogs! His perfect doggy pal would be one that can keep up yet be tolerant of his playful antics. He would benefit from a home willing to exhaust his energy and keep him active . Wishbone might jump on you or play mouth because he is young and still learning. Wishbone will require a home with children 13 years and older because he gets so playful and excited he doesn't realize his size and strength. He truly is a smart young man just needs the right home to spoil him rotten! My past owner went through the process of getting me registered as an Emotional Support Animal as well! And I have the Certificate to prove it!",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/69695.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2d2c50cb-6751-4532-a398-877422a56c44.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/ae164deb-1077-426f-bace-f38307138814.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/c95a20b7-54d9-43a4-a541-159f9eb39a51.jpeg",
    ],
  },
  {
    Name: "Pepper",
    Type: "Dog",
    Breed: "American Pit Bull Cross",
    SecondBreed: "",
    Sex: "Female",
    Color: "White",
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 2,
      Weeks: 4,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23328,
      MicroChipNo: 985113005872880,
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com//photos/lostfound/71168_th_600.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/5ff135bb-000e-4220-8aa0-790af95892c0.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/334112a8-a782-403c-8ea0-36e490a1a486.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2004c2ad-2bf6-4661-90c5-1bcd3378529f.jpg",
    ],
  },
  {
    Name: "Fernando",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23907,
      MicroChipNo: 985113006286714,
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71393.jpg",
    ],
  },
  {
    Name: "Hemingway",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23897,
      MicroChipNo: "",
    },
    Suitability: "<br>Doesn't Like Cats<br>Special Needs",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71387.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/42c9c930-fb07-445b-a08e-cd83c438c515.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/9d5a88d5-bfd5-4d78-b7cd-8e91bdda0bdd.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/34d4696f-2735-4a6e-b266-210357ff5d74.jpeg",
    ],
  },
  {
    Name: "Hemingway",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23897,
      MicroChipNo: "",
    },
    Suitability: "<br>Doesn't Like Cats<br>Special Needs",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71387.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/42c9c930-fb07-445b-a08e-cd83c438c515.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/9d5a88d5-bfd5-4d78-b7cd-8e91bdda0bdd.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/34d4696f-2735-4a6e-b266-210357ff5d74.jpeg",
    ],
  },
];
